CREATE TABLE PRODUCTS (
	PRODUCT_ID INT NOT NULL UNIQUE,
	NAME VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(100),
	WEIGHT NUMERIC(5,2),
	BARCODE VARCHAR(10),
	PRICE NUMERIC(10,2),
	CONSTRAINT PK_PRODUCT_ID PRIMARY KEY(PRODUCT_ID)
)

CREATE TABLE CLIENTS(
	CLIENT_ID INT NOT NULL UNIQUE,
	NAME VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(30),
	BULSTAT INT,
	REGISTERED_DDS VARCHAR(1),
	MOL VARCHAR(20),
	CONSTRAINT PK_CLIENT_ID PRIMARY KEY(CLIENT_ID)
)

CREATE TABLE SALES(
	SALE_ID INT NOT NULL UNIQUE,
	SALE_DATE DATE,
	PRODUCT_ID INT, 
	QUANTITY INT,
	CLIENT_ID INT,
	BILL INT,
	PRICE NUMERIC(20,2),
	CONSTRAINT PK_SALES_ID PRIMARY KEY(SALE_ID),
	CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
	CONSTRAINT FK_CLENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
)

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, PRICE)
VALUES (1,'Bed',100.5)

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, PRICE)
VALUES (2,'Chair',9)

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, PRICE)
VALUES (3,'Sofa',78)

INSERT INTO PRODUCTS (PRODUCT_ID, NAME, PRICE)
VALUES (4,'Table', 50)


INSERT INTO CLIENTS(CLIENT_ID, NAME, BULSTAT, MOL)
VALUES (1,'Ivan OOD', 1234556694, 'Ivan Ivanov')

INSERT INTO CLIENTS(CLIENT_ID, NAME, BULSTAT, MOL)
VALUES (2,'Petar OOD', 94328435, 'Petar Dimov')

INSERT INTO CLIENTS(CLIENT_ID, NAME, BULSTAT, MOL)
VALUES (3,'BST OOD', 32131442, 'Denislav Todorov')

INSERT INTO SALES 
VALUES (1, CONVERT(datetime, '18-9-2019', 105), 2, 3, 1, 129432523, 27)

INSERT INTO SALES 
VALUES (2, CONVERT(datetime, '20-8-2019', 105), 1, 2, 1, 43278324, 201)

INSERT INTO SALES 
VALUES (3, CONVERT(datetime, '15-5-2019', 105), 4, 3, 2, 21214425, 200)

INSERT INTO SALES 
VALUES (4, CONVERT(datetime, '1-07-2019', 105), 3, 1, 3, 754399234, 78)

SELECT * FROM SALES

/* search product by part of the name*/

SELECT * FROM PRODUCTS
WHERE NAME LIKE '%ed'

/* search product and their price and buyer by bill*/

SELECT PR.NAME, PR.PRICE, CS.NAME
FROM PRODUCTS PR JOIN (SELECT C.NAME,S.PRODUCT_ID, S.BILL
						FROM CLIENTS C JOIN SALES S
						ON C.CLIENT_ID = S.CLIENT_ID) AS CS
ON PR.PRODUCT_ID = CS.PRODUCT_ID
WHERE CS.BILL = 129432523

/* name of the company that bought something for the last month*/

SELECT C.NAME
FROM CLIENTS C JOIN SALES S
ON C.CLIENT_ID = S.CLIENT_ID
WHERE S.SALE_DATE > '2019-08-18'

/* quantity of every product that is bought for the last one month*/

SELECT PR.NAME, S.QUANTITY
FROM PRODUCTS PR JOIN SALES S
ON PR.PRODUCT_ID = S.PRODUCT_ID
WHERE S.SALE_DATE > '2019-08-18'
